config:
  argocd:
    serverAddress: "https://argo-cd-argocd-server" 

  registries:
      - name: GitHub Container Registry
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: "username:trueriez password:${docker_password}"

## Mac m1 에서는 Argocd UI에서 도메인을 찾지 못해서 직접 IP를 넣어줬습니다.
hostAliases:
  - ip: 20.200.245.247
    hostnames:
      - github.com
  - ip: 20.200.245.241
    hostnames:
      - ghcr.io
